# Generated by Django 5.1.2 on 2024-11-12 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0003_coupon_discount_amount'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='usage_limit',
            new_name='coupon_limit',
        ),
    ]
