# Generated by Django 5.1.2 on 2024-11-15 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category_offers',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='category_offers',
            name='started_date',
        ),
        migrations.RemoveField(
            model_name='category_offers',
            name='status',
        ),
        migrations.RemoveField(
            model_name='product_offers',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='product_offers',
            name='started_date',
        ),
        migrations.RemoveField(
            model_name='product_offers',
            name='status',
        ),
        migrations.AddField(
            model_name='category_offers',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='category_offers',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_offers',
            name='valid_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product_offers',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
