# Generated by Django 5.1.2 on 2024-11-15 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_remove_category_offers_end_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category_offers',
            old_name='offer_price',
            new_name='offer_discount',
        ),
        migrations.RenameField(
            model_name='product_offers',
            old_name='offer_price',
            new_name='offer_discount',
        ),
    ]
