# Generated by Django 5.1.2 on 2024-10-30 12:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pincode', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_numnber', models.CharField(max_length=255)),
                ('alternative_phone_number', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('landmark', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('address_type', models.CharField(choices=[('H', 'Home'), ('O', 'Office'), ('OT', 'Other')], max_length=12)),
                ('pincode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='picodes', to='pincode.pincode')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
