# Generated by Django 5.1.2 on 2024-10-30 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0003_alter_address_full_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='phone_numnber',
            new_name='phone_number',
        ),
    ]
