# Generated by Django 5.1.2 on 2024-11-03 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0004_rename_phone_numnber_address_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='address_type',
            field=models.CharField(choices=[('Home', 'Home'), ('Other', 'Other')], max_length=12),
        ),
    ]
