# Generated by Django 5.1.2 on 2024-11-05 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0005_alter_address_address_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_listed',
            field=models.BooleanField(default=True),
        ),
    ]
