# Generated by Django 5.1.2 on 2024-11-20 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_orderitem_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='discount_amount',
            new_name='coupon_discount',
        ),
        migrations.AddField(
            model_name='order',
            name='offer_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
