# Generated by Django 5.1.2 on 2024-11-20 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_products_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='stock',
            field=models.DecimalField(decimal_places=1, max_digits=10),
        ),
    ]
