# Generated by Django 5.1.2 on 2024-11-21 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_products_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='deals',
        ),
    ]
