# Generated by Django 5.1.2 on 2024-11-21 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_rename_price_products_price_per_kg_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='price_per_kg',
            new_name='price',
        ),
        migrations.RemoveField(
            model_name='products',
            name='is_piece_based',
        ),
        migrations.DeleteModel(
            name='ProductVariant',
        ),
    ]
