# Generated by Django 5.1.2 on 2024-11-21 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_rename_price_per_kg_products_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='product_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilogram'), ('piece', 'piece')], max_length=50, null=True),
        ),
    ]
