# Generated by Django 5.1.2 on 2024-12-09 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_products_product_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
        migrations.AddField(
            model_name='products',
            name='product_images',
            field=models.JSONField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(3, 'At least 3 images are required'), django.core.validators.MaxLengthValidator(6, 'Maximum 6 images are allowed')]),
        ),
    ]
