# Generated by Django 5.1.2 on 2024-12-09 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_products_product_images_products_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='products',
            name='image3',
        ),
        migrations.AddField(
            model_name='products',
            name='images',
            field=models.JSONField(default=list),
        ),
    ]
